### ISSUE TITLE
undefined:7   "archive_args": [-i", "id_rsa", "-q", "-b", "-", "washington@scans.io"],

### ISSUE THREAD

**Issue by royalterra** [UWNetworksLab/satellite#8]
I try to start this software but say the next:
Can you tell me also how to make the config.json for make a collaborative node say No blacklist set for satellite.
Configure this setting in the config.json file.
You'll need to set up your own blacklist or get in touch with us

```
undefined:7
  "archive_args": [-i", "id_rsa", "-q", "-b", "-", "washington@scans.io"],
                    ^
SyntaxError: Unexpected token i
    at Object.parse (native)
    at Object.<anonymous> (/var/opt/satellite/util/config.js:5:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

```

**Comment by willscott** [comment]
fixed the syntax error in the example configuration, but that file will likely need to be edited at least some as it's copied locally from `config-example.json` to `config.json`.

In particuar, you'll need to

 * Figure out an appropriate list of IP prefixes you want to use as a blacklist (`blacklist_example`)
 * set the local ip / fqdn of the machine scanning (`local_ip`)
 * either get credential for the machine to archive off-site somewhere or comment out https://github.com/UWNetworksLab/satellite/blob/50538bc8f6e1b8b7eccaf443869f27639d23c1fe/fullrun.sh#L120
* get zmap to be okay with the UDP_Multi scanning - which means compiling off of this branch: https://github.com/willscott/zmap/tree/dns_udp
